//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMMI.ECOM.I18N.Auths {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SignInError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignInError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAMMI.ECOM.I18N.Auths.SignInError", typeof(SignInError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận lại mật khẩu không được bỏ trống..
        /// </summary>
        public static string ConfirmPasswordEmpty {
            get {
                return ResourceManager.GetString("ConfirmPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận lại mật khẩu không đúng..
        /// </summary>
        public static string ConfirmPasswordIncorrect {
            get {
                return ResourceManager.GetString("ConfirmPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác..
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP của bạn là {0}. Mã OTP của bạn sẽ hết hạn trong {1}. Bạn vui lòng không chia sẽ mã OTP này đến bất kỳ ai..
        /// </summary>
        public static string NewOTPBody {
            get {
                return ResourceManager.GetString("NewOTPBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một mã OTP đã được gửi đến tài khoản của bạn tại G-Chain.
        /// </summary>
        public static string NewOTPSubject {
            get {
                return ResourceManager.GetString("NewOTPSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới không được bỏ trống..
        /// </summary>
        public static string NewPasswordEmpty {
            get {
                return ResourceManager.GetString("NewPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP đã hết hạn..
        /// </summary>
        public static string OtpExpired {
            get {
                return ResourceManager.GetString("OtpExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP không chính xác..
        /// </summary>
        public static string OtpIncorrect {
            get {
                return ResourceManager.GetString("OtpIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không chính xác..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được bỏ trống.
        /// </summary>
        public static string PaswordEmpty {
            get {
                return ResourceManager.GetString("PaswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đăng nhập không hợp lệ..
        /// </summary>
        public static string RequestInvalid {
            get {
                return ResourceManager.GetString("RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản &apos;{0}&apos; đã bị khóa, vui lòng liên hệ với quản trị viên để biết thêm thông tin..
        /// </summary>
        public static string UserIsLocked {
            get {
                return ResourceManager.GetString("UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không được phép truy cập do thiếu thông tin hoặc chưa được xác thực..
        /// </summary>
        public static string UserIsNotAllow {
            get {
                return ResourceManager.GetString("UserIsNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đã bị tạm khóa trong 30 phút. Vui lòng thử lại sau..
        /// </summary>
        public static string UserIsTempLocked {
            get {
                return ResourceManager.GetString("UserIsTempLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không được bỏ trống.
        /// </summary>
        public static string UserNameEmpty {
            get {
                return ResourceManager.GetString("UserNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản &apos;{0}&apos; không tồn tại hoặc đã bị xóa khỏi hệ thống..
        /// </summary>
        public static string UserNotExisted {
            get {
                return ResourceManager.GetString("UserNotExisted", resourceCulture);
            }
        }

        public static string UserNotVerify
        {
            get
            {
                return ResourceManager.GetString("UserNotVerify", resourceCulture);
            }
        }
    }
}
