//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMMI.ECOM.I18N.Generals {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18nMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18nMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAMMI.ECOM.I18N.Generals.I18nMessage", typeof(I18nMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra, vui lòng thử lại..
        /// </summary>
        public static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin lỗi, đã quá hạn xử lý yêu cầu của bạn. Vui lòng làm mới và thử lại..
        /// </summary>
        public static string AntiForgeryTokenExpired {
            get {
                return ResourceManager.GetString("AntiForgeryTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP không hợp lệ.
        /// </summary>
        public static string ConfirmOtpFailed {
            get {
                return ResourceManager.GetString("ConfirmOtpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung không được để trống..
        /// </summary>
        public static string ContentEmpty {
            get {
                return ResourceManager.GetString("ContentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại địa chỉ không được để trống..
        /// </summary>
        public static string CustomerAddressTypeEmpty {
            get {
                return ResourceManager.GetString("CustomerAddressTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ khách hàng không xác định..
        /// </summary>
        public static string CustomerAddressUndefined {
            get {
                return ResourceManager.GetString("CustomerAddressUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người đánh giá không xác định..
        /// </summary>
        public static string CustomerUndefined {
            get {
                return ResourceManager.GetString("CustomerUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm giữ điểm khi mua hàng..
        /// </summary>
        public static string HoldingPointsAfterBuying {
            get {
                return ResourceManager.GetString("HoldingPointsAfterBuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vĩ độ không được để trống..
        /// </summary>
        public static string LatitudeEmpty {
            get {
                return ResourceManager.GetString("LatitudeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinh độ không được để trống..
        /// </summary>
        public static string LongtitudeEmpty {
            get {
                return ResourceManager.GetString("LongtitudeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phút.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP của bạn là {0}. Mã OTP của bạn sẽ hết hạn trong {1}. Bạn vui lòng không chia sẽ mã OTP này đến bất kỳ ai.  {2}.
        /// </summary>
        public static string NewOTPBody {
            get {
                return ResourceManager.GetString("NewOTPBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một mã OTP đã được gửi đến tài khoản của bạn tại G-Chain.
        /// </summary>
        public static string NewOTPSubject {
            get {
                return ResourceManager.GetString("NewOTPSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần phải có quyền để thực hiện chức năng này..
        /// </summary>
        public static string NotHavePermission {
            get {
                return ResourceManager.GetString("NotHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số OTP được gửi đã vượt quá số lượng cho phép..
        /// </summary>
        public static string NumberOfOtpExceed {
            get {
                return ResourceManager.GetString("NumberOfOtpExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hành động gửi OTP không hợp lệ.
        /// </summary>
        public static string OtpActionInvalid {
            get {
                return ResourceManager.GetString("OtpActionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được phép bỏ trống..
        /// </summary>
        public static string PhoneNumberEmpty {
            get {
                return ResourceManager.GetString("PhoneNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã được sử dụng bởi tài khoản khác..
        /// </summary>
        public static string PhoneNumberIsExisted {
            get {
                return ResourceManager.GetString("PhoneNumberIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không tồn tại trên hệ thống..
        /// </summary>
        public static string PhoneNumberIsNotExisted {
            get {
                return ResourceManager.GetString("PhoneNumberIsNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm được đánh giá không xác định..
        /// </summary>
        public static string ProductUndefined {
            get {
                return ResourceManager.GetString("ProductUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điểm đánh giá không hợp lệ..
        /// </summary>
        public static string RatingValueInvalid {
            get {
                return ResourceManager.GetString("RatingValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} giây.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phút {1} giây.
        /// </summary>
        public static string SecondsAndMinute {
            get {
                return ResourceManager.GetString("SecondsAndMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực không hợp lệ hoặc đã hết hạn..
        /// </summary>
        public static string TokenInvalid {
            get {
                return ResourceManager.GetString("TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không xác định..
        /// </summary>
        public static string UserUndefined {
            get {
                return ResourceManager.GetString("UserUndefined", resourceCulture);
            }
        }
    }
}
